#!/usr/bin/env bash
# dig all subdomains or given subdomain of a domain

echo_line() {
	domain=$1
	subdomain=$2
	full_domain=$subdomain.$domain
	record=$(dig $full_domain | awk '/ANSWER SECTION/{getline; print $4}')
	ip=$(dig $full_domain | awk '/ANSWER SECTION/{getline; print $5}')
	echo "The subdomain $subdomain is a $record record and points to $ip"
}

# Check params
if [ "$#" -eq 0 ]; then
	echo "Usage: $0 <domain> [subdomain]"
	exit 1
fi

if [ "$#" -eq 1 ]; then
	echo_line $1 www
	echo_line $1 lb-01
	echo_line $1 web-01
	echo_line $1 web-02
else
	echo_line $1 $2
fi
