#!/usr/bin/env bash
# Install the load balancer
if ! command -v haproxy &> /dev/null; then
	sudo apt-get update
	sudo apt-get install -y --no-install-recommends software-properties-common
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
	sudo apt-get install -y haproxy=2.8.\*
fi

# Configure the load balancer
content="\

frontend http
		bind *:80
		mode http
		default_backend servers

backend servers
		balance roundrobin
		server web1 54.236.207.221:80 check
		server web2 3.89.146.24:80 check
"
echo "$content" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
