#!usr/bin/env bash
# Install the load balancer

if ! command -v haproxy &> /dev/null; then
	apt-get update
	apt-get install --no-install-recommends software-properties-common
	add-apt-repository ppa:vbernat/haproxy-2.8
	apt-get install haproxy=2.8.\*
fi
