#!/usr/bin/env bash
# backup for all databases

# Check if the password argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <password>"
    exit 1
fi

# MySQL dump file name
dump_file="backup.sql"

# Compressed archive name format: day-month-year.tar.gz
archive_name=$(date +"%d-%m-%Y").tar.gz

# MySQL dump all databases
mysqldump -u root -p"$1" --all-databases > "$dump_file"

# Check if mysqldump was successful
if [ $? -ne 0 ]; then
    echo "MySQL dump failed. Exiting..."
    exit 1
fi

# Compress the MySQL dump file into a tar.gz archive
tar -czf "$archive_name" "$dump_file"

# Check if compression was successful
if [ $? -ne 0 ]; then
    echo "Compression failed. Exiting..."
    exit 1
fi

echo "$dump_file"
